version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - GRPC_HOST=172.18.0.3
    ports:
      - "8081:8081"
    restart: on-failure

networks:
  default:
    name: location-history-mgmt_location-network
    external: true
